baseurl                  = "https://sad-wilson-a543af.netlify.com/" # Your domain name. Must end with "/"
themesDir                = "themes"
publishDir               = "docs"
languageCode             = "de"
defaultContentLanguage   = "de"
isMultilingual           = false
title                    = "Julius Schmitt"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "2006"
    dateformfull         = "2006"
    favicon              = "punkt.png"
    homepage             = "main"                           # What to call the home page link
    footerText           = "[Impressum](/impressum)"

# Metadata for Open Graph and Twitter
    description          = "Julius Schmitt - Filmemacher"               # Max 160 characters show in search results
    images               = ["julius.jpg"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Julius Schmitt"

[[params.mainMenu]]
    link = "/about"
    text = "Hallo"

[[params.mainMenu]]
    link = "/about"
    text = "ich bin Julius"

[[params.mainMenu]]
    link = "/posts"
    text = "Filmemacher"

[[params.mainMenu]]
    link = "https://wirsindcarlo.de"
    text = "und 33,3% von Carlo"

[imaging]
    quality = 75
